
//Set path to SmartSlog KP Library
#include <generic.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_PORT 1
#define INCLUDE_PROPERTY_IP 1
#define INCLUDE_CLASS_MICROPHONESERVICE 1
#define INCLUDE_PROPERTY_HASMAXIMALRANGE 1
#define INCLUDE_PROPERTY_HASMINIMALRANGE 1
#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_STARTTIME 1
#define INCLUDE_PROPERTY_HOLDACTIVITY 1
#define INCLUDE_PROPERTY_TITLE 1
#define INCLUDE_PROPERTY_DELETESPEAKER 1
#define INCLUDE_PROPERTY_XML_FILE 1
#define INCLUDE_PROPERTY_ORGANIZATION 1
#define INCLUDE_PROPERTY_TITLE_SECOND 1
#define INCLUDE_PROPERTY_ENDPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTSLIDENUM 1
#define INCLUDE_PROPERTY_FIRSTTIMESLOT 1
#define INCLUDE_PROPERTY_PERSONLINK 1
#define INCLUDE_PROPERTY_PRESENTS 1
#define INCLUDE_PROPERTY_USERNAME 1
#define INCLUDE_PROPERTY_HASMEASUREMENTPROPERTY 1
#define INCLUDE_PROPERTY_UPDATEPERSONINFO 1
#define INCLUDE_PROPERTY_TOPIC_INTEREST 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_HASAGENDA 1
#define INCLUDE_PROPERTY_STARTCONFERENCE 1
#define INCLUDE_PROPERTY_CURRENTTIMESLOT 1
#define INCLUDE_PROPERTY_CURRENTSLIDECOUNT 1
#define INCLUDE_PROPERTY_HASSERVICE 1
#define INCLUDE_PROPERTY_PERSONINFORMATION 1
#define INCLUDE_PROPERTY_CURRENTSLIDEIMG 1
#define INCLUDE_PROPERTY_DURATION 1
#define INCLUDE_PROPERTY_HASBATTERYLIFETIME 1
#define INCLUDE_PROPERTY_PRESENTATIONTITLE 1
#define INCLUDE_PROPERTY_ADDNEWSPEAKER 1
#define INCLUDE_PROPERTY_POSTERNAME 1
#define INCLUDE_PROPERTY_HASSECTION 1
#define INCLUDE_PROPERTY_UPDATECURRENTTIMESLOT 1
#define INCLUDE_PROPERTY_HASVALUE 1
#define INCLUDE_PROPERTY_DATE 1
#define INCLUDE_PROPERTY_SERVICENAME 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_STARTPRESENTATION 1
#define INCLUDE_PROPERTY_SHOWSLIDE 1
#define INCLUDE_PROPERTY_POSTERID 1
#define INCLUDE_PROPERTY_MISC 1
#define INCLUDE_PROPERTY_UPDATEPRESENTATION 1
#define INCLUDE_PROPERTY_URL 1
#define INCLUDE_PROPERTY_PDATE 1
#define INCLUDE_PROPERTY_ENDCONFERENCE 1
#define INCLUDE_PROPERTY_DESCRIPTION 1
#define INCLUDE_PROPERTY_HASDEVICE 1
#define INCLUDE_PROPERTY_NEWPARTICIPANTCOME 1
#define INCLUDE_PROPERTY_HASCOMMENT 1
#define INCLUDE_PROPERTY_SPEAKERNAME 1
#define INCLUDE_PROPERTY_STATUS 1
#define INCLUDE_PROPERTY_POSTSERVICEID 1
#define INCLUDE_PROPERTY_HASFEATUREOFINTEREST 1
#define INCLUDE_PROPERTY_ACCOUNT 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_HASSENSOR 1
#define INCLUDE_PROPERTY_UPDATEAGENDA 1
#define INCLUDE_PROPERTY_TAGS 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_JOURNAL 1
#define INCLUDE_PROPERTY_HASMEASUREMENTRANGE 1
#define INCLUDE_PROPERTY_LANGUAGE 1
#define INCLUDE_PROPERTY_CURRENTPRESENTATION 1
#define INCLUDE_PROPERTY_HASCONTEXT 1
#define INCLUDE_PROPERTY_NEXTTIMESLOT 1
#define INCLUDE_PROPERTY_STARTCONFERENCEFROM 1
#define INCLUDE_PROPERTY_POSTTITLE 1
#define INCLUDE_PROPERTY_TEXT 1
#define INCLUDE_CLASS_PROFILE 1
#define INCLUDE_CLASS_SENSOR 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_PRESENTATION 1
#define INCLUDE_CLASS_SMARTROOM 1
#define INCLUDE_CLASS_ACTIVITY 1
#define INCLUDE_CLASS_MEASUREMENTPROPERTY 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_BATTERYLIFETIME 1
#define INCLUDE_CLASS_COMMENT 1
#define INCLUDE_CLASS_PROJECTORNOTIFICATION 1
#define INCLUDE_CLASS_POST 1
#define INCLUDE_CLASS_CONFERENCE 1
#define INCLUDE_CLASS_SERVICE 1
#define INCLUDE_CLASS_PROJECTORSERVICE 1
#define INCLUDE_CLASS_AGENDA 1
#define INCLUDE_CLASS_AGENDASERVICE 1
#define INCLUDE_CLASS_LECTION 1
#define INCLUDE_CLASS_FEATUREOFINTEREST 1
#define INCLUDE_CLASS_MEETING 1
#define INCLUDE_CLASS_DEVICE 1
#define INCLUDE_CLASS_AGENDANOTIFICATION 1
#define INCLUDE_CLASS_TRAINING 1
#define INCLUDE_CLASS_MEASUREMENTRANGE 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_AGENDAGUINOTIFICATION 1
#define INCLUDE_CLASS_CONTEXT 1
#define INCLUDE_CLASS_CLIENTNOTIFICATION 1
#define INCLUDE_CLASS_ONLINEACCOUNT 1
#define INCLUDE_CLASS_SECTION 1
#define INCLUDE_CLASS_TIMESLOT 1


#else

#define INCLUDE_PROPERTY_PORT 0
#define INCLUDE_PROPERTY_IP 0
#define INCLUDE_CLASS_MICROPHONESERVICE 0
#define INCLUDE_PROPERTY_HASMAXIMALRANGE 0
#define INCLUDE_PROPERTY_HASMINIMALRANGE 0
#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_STARTTIME 0
#define INCLUDE_PROPERTY_HOLDACTIVITY 0
#define INCLUDE_PROPERTY_TITLE 0
#define INCLUDE_PROPERTY_DELETESPEAKER 0
#define INCLUDE_PROPERTY_XML_FILE 0
#define INCLUDE_PROPERTY_ORGANIZATION 0
#define INCLUDE_PROPERTY_TITLE_SECOND 0
#define INCLUDE_PROPERTY_ENDPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTSLIDENUM 0
#define INCLUDE_PROPERTY_FIRSTTIMESLOT 0
#define INCLUDE_PROPERTY_PERSONLINK 0
#define INCLUDE_PROPERTY_PRESENTS 0
#define INCLUDE_PROPERTY_USERNAME 0
#define INCLUDE_PROPERTY_HASMEASUREMENTPROPERTY 0
#define INCLUDE_PROPERTY_UPDATEPERSONINFO 0
#define INCLUDE_PROPERTY_TOPIC_INTEREST 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_HASAGENDA 0
#define INCLUDE_PROPERTY_STARTCONFERENCE 0
#define INCLUDE_PROPERTY_CURRENTTIMESLOT 0
#define INCLUDE_PROPERTY_CURRENTSLIDECOUNT 0
#define INCLUDE_PROPERTY_HASSERVICE 0
#define INCLUDE_PROPERTY_PERSONINFORMATION 0
#define INCLUDE_PROPERTY_CURRENTSLIDEIMG 0
#define INCLUDE_PROPERTY_DURATION 0
#define INCLUDE_PROPERTY_HASBATTERYLIFETIME 0
#define INCLUDE_PROPERTY_PRESENTATIONTITLE 0
#define INCLUDE_PROPERTY_ADDNEWSPEAKER 0
#define INCLUDE_PROPERTY_POSTERNAME 0
#define INCLUDE_PROPERTY_HASSECTION 0
#define INCLUDE_PROPERTY_UPDATECURRENTTIMESLOT 0
#define INCLUDE_PROPERTY_HASVALUE 0
#define INCLUDE_PROPERTY_DATE 0
#define INCLUDE_PROPERTY_SERVICENAME 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_STARTPRESENTATION 0
#define INCLUDE_PROPERTY_SHOWSLIDE 0
#define INCLUDE_PROPERTY_POSTERID 0
#define INCLUDE_PROPERTY_MISC 0
#define INCLUDE_PROPERTY_UPDATEPRESENTATION 0
#define INCLUDE_PROPERTY_URL 0
#define INCLUDE_PROPERTY_PDATE 0
#define INCLUDE_PROPERTY_ENDCONFERENCE 0
#define INCLUDE_PROPERTY_DESCRIPTION 0
#define INCLUDE_PROPERTY_HASDEVICE 0
#define INCLUDE_PROPERTY_NEWPARTICIPANTCOME 0
#define INCLUDE_PROPERTY_HASCOMMENT 0
#define INCLUDE_PROPERTY_SPEAKERNAME 0
#define INCLUDE_PROPERTY_STATUS 0
#define INCLUDE_PROPERTY_POSTSERVICEID 0
#define INCLUDE_PROPERTY_HASFEATUREOFINTEREST 0
#define INCLUDE_PROPERTY_ACCOUNT 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_HASSENSOR 0
#define INCLUDE_PROPERTY_UPDATEAGENDA 0
#define INCLUDE_PROPERTY_TAGS 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_JOURNAL 0
#define INCLUDE_PROPERTY_HASMEASUREMENTRANGE 0
#define INCLUDE_PROPERTY_LANGUAGE 0
#define INCLUDE_PROPERTY_CURRENTPRESENTATION 0
#define INCLUDE_PROPERTY_HASCONTEXT 0
#define INCLUDE_PROPERTY_NEXTTIMESLOT 0
#define INCLUDE_PROPERTY_STARTCONFERENCEFROM 0
#define INCLUDE_PROPERTY_POSTTITLE 0
#define INCLUDE_PROPERTY_TEXT 0
#define INCLUDE_CLASS_PROFILE 0
#define INCLUDE_CLASS_SENSOR 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_PRESENTATION 0
#define INCLUDE_CLASS_SMARTROOM 0
#define INCLUDE_CLASS_ACTIVITY 0
#define INCLUDE_CLASS_MEASUREMENTPROPERTY 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_BATTERYLIFETIME 0
#define INCLUDE_CLASS_COMMENT 0
#define INCLUDE_CLASS_PROJECTORNOTIFICATION 0
#define INCLUDE_CLASS_POST 0
#define INCLUDE_CLASS_CONFERENCE 0
#define INCLUDE_CLASS_SERVICE 0
#define INCLUDE_CLASS_PROJECTORSERVICE 0
#define INCLUDE_CLASS_AGENDA 0
#define INCLUDE_CLASS_AGENDASERVICE 0
#define INCLUDE_CLASS_LECTION 0
#define INCLUDE_CLASS_FEATUREOFINTEREST 0
#define INCLUDE_CLASS_MEETING 0
#define INCLUDE_CLASS_DEVICE 0
#define INCLUDE_CLASS_AGENDANOTIFICATION 0
#define INCLUDE_CLASS_TRAINING 0
#define INCLUDE_CLASS_MEASUREMENTRANGE 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_AGENDAGUINOTIFICATION 0
#define INCLUDE_CLASS_CONTEXT 0
#define INCLUDE_CLASS_CLIENTNOTIFICATION 0
#define INCLUDE_CLASS_ONLINEACCOUNT 0
#define INCLUDE_CLASS_SECTION 0
#define INCLUDE_CLASS_TIMESLOT 0


#endif

#if INCLUDE_CLASS_MICROPHONESERVICE
extern class_t *CLASS_MICROPHONESERVICE;
#endif
#if INCLUDE_CLASS_PROFILE
extern class_t *CLASS_PROFILE;
#endif
#if INCLUDE_CLASS_SENSOR
extern class_t *CLASS_SENSOR;
#endif
#if INCLUDE_CLASS_NOTHING
extern class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_PRESENTATION
extern class_t *CLASS_PRESENTATION;
#endif
#if INCLUDE_CLASS_SMARTROOM
extern class_t *CLASS_SMARTROOM;
#endif
#if INCLUDE_CLASS_ACTIVITY
extern class_t *CLASS_ACTIVITY;
#endif
#if INCLUDE_CLASS_MEASUREMENTPROPERTY
extern class_t *CLASS_MEASUREMENTPROPERTY;
#endif
#if INCLUDE_CLASS_PERSON
extern class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_BATTERYLIFETIME
extern class_t *CLASS_BATTERYLIFETIME;
#endif
#if INCLUDE_CLASS_COMMENT
extern class_t *CLASS_COMMENT;
#endif
#if INCLUDE_CLASS_PROJECTORNOTIFICATION
extern class_t *CLASS_PROJECTORNOTIFICATION;
#endif
#if INCLUDE_CLASS_POST
extern class_t *CLASS_POST;
#endif
#if INCLUDE_CLASS_CONFERENCE
extern class_t *CLASS_CONFERENCE;
#endif
#if INCLUDE_CLASS_SERVICE
extern class_t *CLASS_SERVICE;
#endif
#if INCLUDE_CLASS_PROJECTORSERVICE
extern class_t *CLASS_PROJECTORSERVICE;
#endif
#if INCLUDE_CLASS_AGENDA
extern class_t *CLASS_AGENDA;
#endif
#if INCLUDE_CLASS_AGENDASERVICE
extern class_t *CLASS_AGENDASERVICE;
#endif
#if INCLUDE_CLASS_LECTION
extern class_t *CLASS_LECTION;
#endif
#if INCLUDE_CLASS_FEATUREOFINTEREST
extern class_t *CLASS_FEATUREOFINTEREST;
#endif
#if INCLUDE_CLASS_MEETING
extern class_t *CLASS_MEETING;
#endif
#if INCLUDE_CLASS_DEVICE
extern class_t *CLASS_DEVICE;
#endif
#if INCLUDE_CLASS_AGENDANOTIFICATION
extern class_t *CLASS_AGENDANOTIFICATION;
#endif
#if INCLUDE_CLASS_TRAINING
extern class_t *CLASS_TRAINING;
#endif
#if INCLUDE_CLASS_MEASUREMENTRANGE
extern class_t *CLASS_MEASUREMENTRANGE;
#endif
#if INCLUDE_CLASS_THING
extern class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_AGENDAGUINOTIFICATION
extern class_t *CLASS_AGENDAGUINOTIFICATION;
#endif
#if INCLUDE_CLASS_CONTEXT
extern class_t *CLASS_CONTEXT;
#endif
#if INCLUDE_CLASS_CLIENTNOTIFICATION
extern class_t *CLASS_CLIENTNOTIFICATION;
#endif
#if INCLUDE_CLASS_ONLINEACCOUNT
extern class_t *CLASS_ONLINEACCOUNT;
#endif
#if INCLUDE_CLASS_SECTION
extern class_t *CLASS_SECTION;
#endif
#if INCLUDE_CLASS_TIMESLOT
extern class_t *CLASS_TIMESLOT;
#endif

#if INCLUDE_PROPERTY_PORT
extern property_t *PROPERTY_PORT;
#endif
#if INCLUDE_PROPERTY_IP
extern property_t *PROPERTY_IP;
#endif
#if INCLUDE_PROPERTY_HASMAXIMALRANGE
extern property_t *PROPERTY_HASMAXIMALRANGE;
#endif
#if INCLUDE_PROPERTY_HASMINIMALRANGE
extern property_t *PROPERTY_HASMINIMALRANGE;
#endif
#if INCLUDE_PROPERTY_MBOX
extern property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_STARTTIME
extern property_t *PROPERTY_STARTTIME;
#endif
#if INCLUDE_PROPERTY_HOLDACTIVITY
extern property_t *PROPERTY_HOLDACTIVITY;
#endif
#if INCLUDE_PROPERTY_TITLE
extern property_t *PROPERTY_TITLE;
#endif
#if INCLUDE_PROPERTY_DELETESPEAKER
extern property_t *PROPERTY_DELETESPEAKER;
#endif
#if INCLUDE_PROPERTY_XML_FILE
extern property_t *PROPERTY_XML_FILE;
#endif
#if INCLUDE_PROPERTY_ORGANIZATION
extern property_t *PROPERTY_ORGANIZATION;
#endif
#if INCLUDE_PROPERTY_TITLE_SECOND
extern property_t *PROPERTY_TITLE_SECOND;
#endif
#if INCLUDE_PROPERTY_ENDPRESENTATION
extern property_t *PROPERTY_ENDPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDENUM
extern property_t *PROPERTY_CURRENTSLIDENUM;
#endif
#if INCLUDE_PROPERTY_FIRSTTIMESLOT
extern property_t *PROPERTY_FIRSTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_PERSONLINK
extern property_t *PROPERTY_PERSONLINK;
#endif
#if INCLUDE_PROPERTY_PRESENTS
extern property_t *PROPERTY_PRESENTS;
#endif
#if INCLUDE_PROPERTY_USERNAME
extern property_t *PROPERTY_USERNAME;
#endif
#if INCLUDE_PROPERTY_HASMEASUREMENTPROPERTY
extern property_t *PROPERTY_HASMEASUREMENTPROPERTY;
#endif
#if INCLUDE_PROPERTY_UPDATEPERSONINFO
extern property_t *PROPERTY_UPDATEPERSONINFO;
#endif
#if INCLUDE_PROPERTY_TOPIC_INTEREST
extern property_t *PROPERTY_TOPIC_INTEREST;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_PHONE
extern property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_HASAGENDA
extern property_t *PROPERTY_HASAGENDA;
#endif
#if INCLUDE_PROPERTY_STARTCONFERENCE
extern property_t *PROPERTY_STARTCONFERENCE;
#endif
#if INCLUDE_PROPERTY_CURRENTTIMESLOT
extern property_t *PROPERTY_CURRENTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDECOUNT
extern property_t *PROPERTY_CURRENTSLIDECOUNT;
#endif
#if INCLUDE_PROPERTY_HASSERVICE
extern property_t *PROPERTY_HASSERVICE;
#endif
#if INCLUDE_PROPERTY_PERSONINFORMATION
extern property_t *PROPERTY_PERSONINFORMATION;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDEIMG
extern property_t *PROPERTY_CURRENTSLIDEIMG;
#endif
#if INCLUDE_PROPERTY_DURATION
extern property_t *PROPERTY_DURATION;
#endif
#if INCLUDE_PROPERTY_HASBATTERYLIFETIME
extern property_t *PROPERTY_HASBATTERYLIFETIME;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONTITLE
extern property_t *PROPERTY_PRESENTATIONTITLE;
#endif
#if INCLUDE_PROPERTY_ADDNEWSPEAKER
extern property_t *PROPERTY_ADDNEWSPEAKER;
#endif
#if INCLUDE_PROPERTY_POSTERNAME
extern property_t *PROPERTY_POSTERNAME;
#endif
#if INCLUDE_PROPERTY_HASSECTION
extern property_t *PROPERTY_HASSECTION;
#endif
#if INCLUDE_PROPERTY_UPDATECURRENTTIMESLOT
extern property_t *PROPERTY_UPDATECURRENTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_HASVALUE
extern property_t *PROPERTY_HASVALUE;
#endif
#if INCLUDE_PROPERTY_DATE
extern property_t *PROPERTY_DATE;
#endif
#if INCLUDE_PROPERTY_SERVICENAME
extern property_t *PROPERTY_SERVICENAME;
#endif
#if INCLUDE_PROPERTY_NAME
extern property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_STARTPRESENTATION
extern property_t *PROPERTY_STARTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_SHOWSLIDE
extern property_t *PROPERTY_SHOWSLIDE;
#endif
#if INCLUDE_PROPERTY_POSTERID
extern property_t *PROPERTY_POSTERID;
#endif
#if INCLUDE_PROPERTY_MISC
extern property_t *PROPERTY_MISC;
#endif
#if INCLUDE_PROPERTY_UPDATEPRESENTATION
extern property_t *PROPERTY_UPDATEPRESENTATION;
#endif
#if INCLUDE_PROPERTY_URL
extern property_t *PROPERTY_URL;
#endif
#if INCLUDE_PROPERTY_PDATE
extern property_t *PROPERTY_PDATE;
#endif
#if INCLUDE_PROPERTY_ENDCONFERENCE
extern property_t *PROPERTY_ENDCONFERENCE;
#endif
#if INCLUDE_PROPERTY_DESCRIPTION
extern property_t *PROPERTY_DESCRIPTION;
#endif
#if INCLUDE_PROPERTY_HASDEVICE
extern property_t *PROPERTY_HASDEVICE;
#endif
#if INCLUDE_PROPERTY_NEWPARTICIPANTCOME
extern property_t *PROPERTY_NEWPARTICIPANTCOME;
#endif
#if INCLUDE_PROPERTY_HASCOMMENT
extern property_t *PROPERTY_HASCOMMENT;
#endif
#if INCLUDE_PROPERTY_SPEAKERNAME
extern property_t *PROPERTY_SPEAKERNAME;
#endif
#if INCLUDE_PROPERTY_STATUS
extern property_t *PROPERTY_STATUS;
#endif
#if INCLUDE_PROPERTY_POSTSERVICEID
extern property_t *PROPERTY_POSTSERVICEID;
#endif
#if INCLUDE_PROPERTY_HASFEATUREOFINTEREST
extern property_t *PROPERTY_HASFEATUREOFINTEREST;
#endif
#if INCLUDE_PROPERTY_ACCOUNT
extern property_t *PROPERTY_ACCOUNT;
#endif
#if INCLUDE_PROPERTY_AGE
extern property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_HASSENSOR
extern property_t *PROPERTY_HASSENSOR;
#endif
#if INCLUDE_PROPERTY_UPDATEAGENDA
extern property_t *PROPERTY_UPDATEAGENDA;
#endif
#if INCLUDE_PROPERTY_TAGS
extern property_t *PROPERTY_TAGS;
#endif
#if INCLUDE_PROPERTY_IMG
extern property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_JOURNAL
extern property_t *PROPERTY_JOURNAL;
#endif
#if INCLUDE_PROPERTY_HASMEASUREMENTRANGE
extern property_t *PROPERTY_HASMEASUREMENTRANGE;
#endif
#if INCLUDE_PROPERTY_LANGUAGE
extern property_t *PROPERTY_LANGUAGE;
#endif
#if INCLUDE_PROPERTY_CURRENTPRESENTATION
extern property_t *PROPERTY_CURRENTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_HASCONTEXT
extern property_t *PROPERTY_HASCONTEXT;
#endif
#if INCLUDE_PROPERTY_NEXTTIMESLOT
extern property_t *PROPERTY_NEXTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_STARTCONFERENCEFROM
extern property_t *PROPERTY_STARTCONFERENCEFROM;
#endif
#if INCLUDE_PROPERTY_POSTTITLE
extern property_t *PROPERTY_POSTTITLE;
#endif
#if INCLUDE_PROPERTY_TEXT
extern property_t *PROPERTY_TEXT;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
